reward:
  scales:
    pose: 1.0
sampler:
  num_segments: 20
  temperature: 1.0
max_episode_length: 20 # seconds
global_obs: True
root_height_obs: True
pose_termination: True
pose_termination_dist: 1.0 # m
enable_phase_obs: False
enable_tar_obs: True
num_phase_encoding: 4
tar_obs_steps: [1, 3, 5, 7]
num_disc_obs_steps: 1
rand_reset: True
zero_center_action: True
log_tracking_error: True

visualize_ref_char: False
ref_char_offset: [0, -2.0, 0.0] # m

enable_early_termination: True
termination_height: 0.3
enable_vel_obs: False # Controls root vel, root ang vel, and dof vel observations

contact_bodies: ["left_knee_link", "left_ankle_pitch_link", "left_ankle_roll_link", "right_knee_link", "right_ankle_pitch_link", "right_ankle_roll_link"]

motion_file: "assets/motions/dance1_subject3.motion"
motion_joint_order:
  - left_hip_pitch_joint
  - left_hip_roll_joint
  - left_hip_yaw_joint
  - left_knee_joint
  - left_ankle_pitch_joint
  - left_ankle_roll_joint
  - right_hip_pitch_joint
  - right_hip_roll_joint
  - right_hip_yaw_joint
  - right_knee_joint
  - right_ankle_pitch_joint
  - right_ankle_roll_joint
  - waist_yaw_joint
  - waist_roll_joint
  - waist_pitch_joint
  - left_shoulder_pitch_joint
  - left_shoulder_roll_joint
  - left_shoulder_yaw_joint
  - left_elbow_joint
  - left_wrist_roll_joint
  - left_wrist_pitch_joint
  - left_wrist_yaw_joint
  - right_shoulder_pitch_joint
  - right_shoulder_roll_joint
  - right_shoulder_yaw_joint
  - right_elbow_joint
  - right_wrist_roll_joint
  - right_wrist_pitch_joint
  - right_wrist_yaw_joint

reward_pose_w: 0.5
reward_vel_w: 0.1
reward_root_pose_w: 0.15
reward_root_vel_w: 0.1

reward_pose_scale: 0.25
reward_vel_scale: 0.01
reward_root_pose_scale: 5.0
reward_root_vel_scale: 1.0